// 300+ Glide API match pairs grouped by difficulty tier.
// Tiers scale: easy -> medium -> hard -> expert, mixed into rounds as the
// player progresses through levels.

export type Pair = { api: string; desc: string };

// ---------- EASY (basics every dev sees on day one) ----------
export const EASY: Pair[] = [
  { api: "GlideRecord.get()", desc: "Fetch a single record by sys_id or field=value" },
  { api: "GlideRecord.addQuery()", desc: "Add a filter to the encoded query" },
  { api: "GlideRecord.query()", desc: "Execute the built-up GlideRecord query" },
  { api: "GlideRecord.next()", desc: "Advance to the next row in a result set" },
  { api: "GlideRecord.hasNext()", desc: "Return true if more rows remain" },
  { api: "GlideRecord.update()", desc: "Persist field changes on a fetched record" },
  { api: "GlideRecord.insert()", desc: "Create a new record and return its sys_id" },
  { api: "GlideRecord.deleteRecord()", desc: "Delete the current record from the table" },
  { api: "GlideRecord.initialize()", desc: "Prepare an empty record for insertion" },
  { api: "GlideRecord.getValue()", desc: "Get a field's raw string value" },
  { api: "GlideRecord.getDisplayValue()", desc: "Get a field's human-readable label" },
  { api: "GlideRecord.setValue()", desc: "Set a field value before insert/update" },
  { api: "GlideRecord.setLimit()", desc: "Cap the number of rows the query returns" },
  { api: "GlideRecord.orderBy()", desc: "Sort results ascending by a field" },
  { api: "GlideRecord.orderByDesc()", desc: "Sort results descending by a field" },
  { api: "GlideRecord.getRowCount()", desc: "Total rows the executed query returned" },
  { api: "GlideRecord.isValidRecord()", desc: "True if the current row points to a real record" },
  { api: "GlideRecord.canRead()", desc: "True if the current user can read this row" },
  { api: "GlideRecord.canWrite()", desc: "True if the current user can write this row" },
  { api: "gs.info()", desc: "Log an INFO line to the system log" },
  { api: "gs.warn()", desc: "Log a WARN line to the system log" },
  { api: "gs.error()", desc: "Log an ERROR line to the system log" },
  { api: "gs.log()", desc: "Write a basic log line (global scope)" },
  { api: "gs.addInfoMessage()", desc: "Show a non-blocking info banner to the user" },
  { api: "gs.addErrorMessage()", desc: "Show a red error banner to the user" },
  { api: "gs.getUserID()", desc: "sys_id of the currently logged-in user" },
  { api: "gs.getUserName()", desc: "User name (login id) of the current user" },
  { api: "gs.getUser()", desc: "Return a GlideUser for the current session" },
  { api: "gs.nil()", desc: "True when a value is null, undefined or empty string" },
  { api: "gs.eventQueue()", desc: "Queue an event for async processing" },
  { api: "gs.getProperty()", desc: "Read a sys_properties value as string" },
  { api: "gs.hasRole()", desc: "True if the current user has the given role" },
  { api: "current.setAbortAction()", desc: "Stop a Business Rule's DB operation" },
  { api: "g_form.getValue()", desc: "Read a field value from the client form" },
  { api: "g_form.setValue()", desc: "Set a field value on the client form" },
  { api: "g_form.setMandatory()", desc: "Toggle a field's mandatory flag in the UI" },
  { api: "g_form.setReadOnly()", desc: "Toggle a field's read-only flag in the UI" },
  { api: "g_form.setVisible()", desc: "Show or hide a field on the form" },
  { api: "g_form.addInfoMessage()", desc: "Show an info message above the form" },
  { api: "g_form.addErrorMessage()", desc: "Show an error message above the form" },
];

// ---------- MEDIUM (everyday scripting) ----------
export const MEDIUM: Pair[] = [
  { api: "GlideRecord.addEncodedQuery()", desc: "Apply a full encoded-query string to the GR" },
  { api: "GlideRecord.addNotNullQuery()", desc: "Filter rows where a field is not empty" },
  { api: "GlideRecord.addNullQuery()", desc: "Filter rows where a field is empty" },
  { api: "GlideRecord.addActiveQuery()", desc: "Restrict to rows with active=true" },
  { api: "GlideRecord.addInactiveQuery()", desc: "Restrict to rows with active=false" },
  { api: "GlideRecord.addOrCondition()", desc: "Chain an OR clause onto the previous query" },
  { api: "GlideRecord.addJoinQuery()", desc: "Join another table into the current query" },
  { api: "GlideRecord.setWorkflow()", desc: "Enable or disable business rules for this op" },
  { api: "GlideRecord.autoSysFields()", desc: "Toggle automatic sys_* field updates" },
  { api: "GlideRecord.updateMultiple()", desc: "Update every row matched by the query" },
  { api: "GlideRecord.deleteMultiple()", desc: "Delete every row matched by the query" },
  { api: "GlideRecord.getEncodedQuery()", desc: "Return the encoded query of the current GR" },
  { api: "GlideRecord.getUniqueValue()", desc: "Return the sys_id of the current row" },
  { api: "GlideRecord.getTableName()", desc: "Name of the table this GR targets" },
  { api: "GlideRecord.changes()", desc: "True if any field on the current row changed" },
  { api: "GlideRecord.operation()", desc: "Returns 'insert', 'update', or 'delete'" },
  { api: "GlideElement.changes()", desc: "True if this specific field changed" },
  { api: "GlideElement.changesFrom()", desc: "True if the field changed from a given value" },
  { api: "GlideElement.changesTo()", desc: "True if the field changed to a given value" },
  { api: "GlideElement.getDisplayValue()", desc: "Display value for a single field" },
  { api: "GlideElement.getLabel()", desc: "The column label as shown on forms" },
  { api: "GlideElement.canRead()", desc: "True if current user can read this field" },
  { api: "GlideElement.canWrite()", desc: "True if current user can write this field" },
  { api: "GlideElement.nil()", desc: "True if this field is null or empty" },
  { api: "GlideDateTime.getNumericValue()", desc: "Epoch milliseconds since 1970 UTC" },
  { api: "GlideDateTime.getDisplayValue()", desc: "Formatted in the user's time zone" },
  { api: "GlideDateTime.subtract()", desc: "Subtract a duration from a datetime" },
  { api: "GlideDateTime.add()", desc: "Add a duration to a datetime" },
  { api: "GlideDateTime.addSeconds()", desc: "Shift a datetime by N seconds" },
  { api: "GlideDateTime.addDays()", desc: "Shift a datetime by N calendar days" },
  { api: "GlideDateTime.compareTo()", desc: "-1/0/1 comparison between two datetimes" },
  { api: "GlideDateTime.getDate()", desc: "Return the date portion as a GlideDate" },
  { api: "GlideDateTime.getTime()", desc: "Return the time portion as a GlideTime" },
  { api: "GlideDateTime.now()", desc: "Current datetime in the user's time zone" },
  { api: "GlideDate.subtract()", desc: "Number of days between two GlideDates" },
  { api: "gs.daysAgo()", desc: "GlideDate string for N days before today" },
  { api: "gs.daysAgoStart()", desc: "Datetime for the start of N days ago" },
  { api: "gs.beginningOfThisWeek()", desc: "Datetime at the start of the current week" },
  { api: "gs.endOfThisMonth()", desc: "Datetime at the end of the current month" },
  { api: "gs.getSession()", desc: "GlideSession for the current request" },
  { api: "gs.getMessage()", desc: "Look up a translated message by key" },
  { api: "gs.eventQueueScheduled()", desc: "Queue an event to fire at a future time" },
  { api: "gs.executeNow()", desc: "Run a sys_trigger record immediately" },
  { api: "gs.generateGUID()", desc: "Return a fresh 32-character sys_id" },
  { api: "gs.tableExists()", desc: "True if a table with this name exists" },
  { api: "gs.setProperty()", desc: "Update a sys_properties value at runtime" },
  { api: "gs.hasRoleInGroup()", desc: "True if user holds role in a specific group" },
  { api: "GlideUser.hasRole()", desc: "True if the GlideUser holds the named role" },
  { api: "GlideUser.isMemberOf()", desc: "True if user belongs to the given group" },
  { api: "GlideUser.getRoles()", desc: "Array of roles assigned to the user" },
  { api: "GlideUser.getFirstName()", desc: "First name of the GlideUser" },
  { api: "GlideUser.getLastName()", desc: "Last name of the GlideUser" },
  { api: "GlideUser.getEmail()", desc: "Email address for the GlideUser" },
  { api: "GlideUser.getMyGroups()", desc: "Set of groups the user is in" },
  { api: "GlideAjax.addParam()", desc: "Set a parameter on a client-to-server AJAX call" },
  { api: "GlideAjax.getXMLAnswer()", desc: "Synchronously fetch the script include answer" },
  { api: "GlideAjax.getXML()", desc: "Async call that invokes a response callback" },
  { api: "g_form.clearValue()", desc: "Clear a field's value on the form" },
  { api: "g_form.clearMessages()", desc: "Remove all field/form messages from the UI" },
  { api: "g_form.showFieldMsg()", desc: "Display a message below a specific field" },
  { api: "g_form.hideFieldMsg()", desc: "Hide messages shown below a field" },
  { api: "g_form.save()", desc: "Save the form without leaving the page" },
  { api: "g_form.submit()", desc: "Submit the form, optionally with a UI action" },
  { api: "g_form.isNewRecord()", desc: "True if the form is for an unsaved record" },
  { api: "g_form.getReference()", desc: "Async fetch of the referenced GlideRecord" },
  { api: "g_form.getControl()", desc: "Return the DOM element for a field" },
  { api: "g_user.hasRole()", desc: "Client-side check for a role on the current user" },
  { api: "g_user.hasRoleExactly()", desc: "Match a role on the user without inheritance" },
  { api: "GlideAggregate.addAggregate()", desc: "Add COUNT/SUM/AVG to a grouped query" },
  { api: "GlideAggregate.groupBy()", desc: "Group aggregated results by a field" },
  { api: "GlideAggregate.getAggregate()", desc: "Read the aggregate value of the current row" },
];

// ---------- HARD (server-side internals & integrations) ----------
export const HARD: Pair[] = [
  { api: "GlideRecord.setUseEngines()", desc: "Toggle data policy/security engines for the op" },
  { api: "GlideRecord.setForceUpdate()", desc: "Update the row even when no field changed" },
  { api: "GlideRecord.applyTemplate()", desc: "Apply a sys_template's defaults to the record" },
  { api: "GlideRecord.chooseWindow()", desc: "Query a row window between two offsets" },
  { api: "GlideRecord.isNewRecord()", desc: "True before insert() has been called" },
  { api: "GlideRecord.isActionAborted()", desc: "True if setAbortAction(true) was called" },
  { api: "GlideRecord.getRelatedLists()", desc: "Return related-list definitions for the table" },
  { api: "GlideRecord.setCategorizedQuery()", desc: "Apply a categorized encoded-query block" },
  { api: "GlideRecord.deleteMultiple({chunk})", desc: "Delete in chunks to avoid long transactions" },
  { api: "GlideRecord.setNewGuidValue()", desc: "Force a specific sys_id on insert" },
  { api: "GlideRecord.insertWithReferences()", desc: "Insert and cascade reference records" },
  { api: "GlideRecord.autoSysFields(false)", desc: "Skip sys_updated_on/by during write" },
  { api: "GlideRecordSecure", desc: "GR variant that enforces ACLs on every read" },
  { api: "GlideQuery.where()", desc: "Fluent builder filter clause" },
  { api: "GlideQuery.select()", desc: "Pick fields to return from a GlideQuery" },
  { api: "GlideQuery.insert()", desc: "Insert a record via the fluent GlideQuery API" },
  { api: "GlideQuery.update()", desc: "Update records via the fluent GlideQuery API" },
  { api: "GlideQuery.forEach()", desc: "Iterate every result of a GlideQuery" },
  { api: "GlideRecord.setQueryReferences()", desc: "Allow dot-walking in the encoded query" },
  { api: "GlideRecord.getLink()", desc: "URL to view this record in the UI" },
  { api: "GlideRecord.getClassDisplayValue()", desc: "Label of the row's actual class (table)" },
  { api: "GlideElement.getReferenceTable()", desc: "Name of the table this reference points to" },
  { api: "GlideElement.getED()", desc: "GlideElementDescriptor for type metadata" },
  { api: "GlideElement.getChoices()", desc: "Array of allowed choice values for the field" },
  { api: "GlideElement.getJournalEntry()", desc: "Return journal entries newest or oldest" },
  { api: "GlideDateTime.setDisplayValue()", desc: "Parse a user-formatted string into the datetime" },
  { api: "GlideDateTime.setValue()", desc: "Set the internal UTC value of the datetime" },
  { api: "GlideDateTime.getLocalDate()", desc: "Date portion in the user's time zone" },
  { api: "GlideDateTime.getTZOffset()", desc: "Time-zone offset from UTC in ms" },
  { api: "GlideDuration.getDurationValue()", desc: "Duration string like '1 Day 2 Hours'" },
  { api: "GlideSchedule.duration()", desc: "Working-time between two datetimes for a schedule" },
  { api: "GlideSchedule.isInSchedule()", desc: "True if a datetime falls inside the schedule" },
  { api: "GlideCalendarDateTime", desc: "Datetime aware of business calendars" },
  { api: "GlideSystem.getCurrentScopeName()", desc: "Return the active application scope name" },
  { api: "GlideSession.getRoles()", desc: "Roles currently active on the session" },
  { api: "GlideSession.getClientIP()", desc: "IP address of the calling client" },
  { api: "GlideSession.getCurrentApplicationId()", desc: "sys_id of the active scoped app" },
  { api: "GlideTransaction.get()", desc: "Get the current transaction handle" },
  { api: "GlideTransaction.cancel()", desc: "Mark the current transaction for cancellation" },
  { api: "RESTMessageV2.setEndpoint()", desc: "Set the URL for an outbound REST call" },
  { api: "RESTMessageV2.setHttpMethod()", desc: "Choose GET/POST/PUT/DELETE on the message" },
  { api: "RESTMessageV2.setRequestBody()", desc: "Attach a raw body string to the request" },
  { api: "RESTMessageV2.setRequestHeader()", desc: "Add or override an outbound HTTP header" },
  { api: "RESTMessageV2.setBasicAuth()", desc: "Configure basic auth on the request" },
  { api: "RESTMessageV2.executeAsync()", desc: "Send the request without blocking the script" },
  { api: "RESTResponseV2.getBody()", desc: "Read the response body as a string" },
  { api: "RESTResponseV2.getStatusCode()", desc: "Numeric HTTP status of the response" },
  { api: "RESTResponseV2.getHeaders()", desc: "Map of all response headers" },
  { api: "SOAPMessageV2.execute()", desc: "Invoke an outbound SOAP request synchronously" },
  { api: "sn_ws.RESTAPIRequest", desc: "Inbound REST request object inside a Scripted API" },
  { api: "sn_ws.RESTAPIResponse", desc: "Inbound REST response builder in Scripted APIs" },
  { api: "sn_ws.RESTAPIResponse.setStatus()", desc: "Set the HTTP status on a scripted REST reply" },
  { api: "sn_ws.RESTAPIResponse.setBody()", desc: "Serialize a body onto a scripted REST reply" },
  { api: "sn_ws.RESTAPIResponse.getStreamWriter()", desc: "Stream large payloads chunk by chunk" },
  { api: "sn_ws_err.BadRequestError", desc: "Throw a 400 from a Scripted REST resource" },
  { api: "sn_ws_err.NotFoundError", desc: "Throw a 404 from a Scripted REST resource" },
  { api: "GlideEncrypter.encrypt()", desc: "Symmetric encrypt a string with the instance key" },
  { api: "GlideEncrypter.decrypt()", desc: "Decrypt a string previously encrypted by the instance" },
  { api: "GlideDigest.getSHA256Base64()", desc: "SHA-256 hash of a string, base64-encoded" },
  { api: "GlideSecureRandomUtil.getSecureRandomInt()", desc: "Cryptographically strong random integer" },
  { api: "GlideSecurityUtils.escapeHTML()", desc: "Escape user input before embedding into HTML" },
  { api: "GlideEmailOutbound.send()", desc: "Send a fully built outbound email immediately" },
  { api: "GlideEmailOutbound.addRecipient()", desc: "Add a To: recipient to an outbound email" },
  { api: "GlideEmailOutbound.setSubject()", desc: "Set the subject line on the outbound email" },
  { api: "EmailWatermark.getWatermark()", desc: "Watermark token used to thread inbound replies" },
];

// ---------- EXPERT (advanced / niche / platform) ----------
export const EXPERT: Pair[] = [
  { api: "GlideMultipleUpdate.execute()", desc: "Apply a prepared multi-row update in one DB op" },
  { api: "GlideRecord.setStrategy()", desc: "Hint the DB query planner for big tables" },
  { api: "GlideRecord.setEnforceTextIndex()", desc: "Force a text-index path for matching queries" },
  { api: "GlideRecord.queryNoDomain()", desc: "Run the query bypassing domain separation" },
  { api: "GlideRecord.setDomain()", desc: "Switch the active domain context for the GR" },
  { api: "GlideRecord.applyEncodedQuery()", desc: "Apply an encoded query directly to the GR" },
  { api: "GlideAggregate.addHaving()", desc: "Filter aggregated rows after grouping" },
  { api: "GlideAggregate.addTrend()", desc: "Add a time-trend bucket to the aggregate" },
  { api: "GlideAggregate.getTotal()", desc: "Sum the aggregate across all groups" },
  { api: "GlideImportSetTransformer.transformAllMaps()", desc: "Run every transform map on an import set" },
  { api: "GlideImportSetRun.getRowsInserted()", desc: "Count of rows inserted by a transform" },
  { api: "GlideUpdateManager2.saveRecord()", desc: "Capture a record into the current update set" },
  { api: "GlideUpdateManager2.removeRecord()", desc: "Remove a record from the current update set" },
  { api: "GlideAppCreatorAPI.publishApp()", desc: "Publish a scoped app version programmatically" },
  { api: "GlideMutex.lock()", desc: "Acquire a cluster-safe named mutex" },
  { api: "GlideMutex.unlock()", desc: "Release a previously acquired named mutex" },
  { api: "GlideSemaphore.acquire()", desc: "Take a slot from a cluster semaphore" },
  { api: "GlideExecutionTracker", desc: "Tracker that reports progress for long-running scripts" },
  { api: "GlideExecutionTracker.run()", desc: "Begin execution and emit progress events" },
  { api: "GlideScheduleItem.duration()", desc: "Duration between two datetimes on a schedule item" },
  { api: "GlideScheduleDateTime", desc: "Datetime tied to a specific business schedule" },
  { api: "WorkflowApprovalUtils.cancelAll()", desc: "Cancel every pending approval on a record" },
  { api: "WorkflowApprovalUtils.reset()", desc: "Reset approvals so they can be re-evaluated" },
  { api: "Workflow.cancel()", desc: "Cancel a running classic workflow context" },
  { api: "Workflow.restartWorkflow()", desc: "Restart a workflow from the beginning" },
  { api: "sn_fd.FlowAPI.executeFlow()", desc: "Run a Flow Designer flow from server script" },
  { api: "sn_fd.FlowAPI.executeSubflow()", desc: "Invoke a subflow with typed inputs" },
  { api: "sn_fd.FlowAPI.getRunner()", desc: "Builder for executing a flow or action" },
  { api: "sn_fd.FlowAPI.executeAction()", desc: "Run a single Flow Designer action" },
  { api: "GlideCatalogItem.addToCart()", desc: "Add a catalog item with variables to the cart" },
  { api: "CartJS.addToCart()", desc: "Server-side helper to add an item to the cart" },
  { api: "CartJS.checkoutCart()", desc: "Submit the current cart as a request" },
  { api: "GlideRecordSecure.canCreate()", desc: "ACL-aware check for create permission" },
  { api: "GlideRecord.getDisplayClassName()", desc: "Label of the row's table class" },
  { api: "GlideRecord.getCategorizedAttribute()", desc: "Read a categorized dictionary attribute" },
  { api: "GlideEvaluator.evaluateString()", desc: "Sandbox-evaluate a small script string" },
  { api: "GlideStringUtil.escapeHTML()", desc: "Escape a string for safe HTML rendering" },
  { api: "GlideStringUtil.base64Encode()", desc: "Base64-encode a UTF-8 string" },
  { api: "GlideStringUtil.base64Decode()", desc: "Decode a base64 string into UTF-8" },
  { api: "GlideXMLUtil.removeInvalidChars()", desc: "Strip illegal XML characters from a string" },
  { api: "GlideXMLDocument.parse()", desc: "Parse an XML string into a navigable document" },
  { api: "XMLDocument2.setNamespaceAware()", desc: "Honor namespaces while traversing XML" },
  { api: "JSONParser.parse()", desc: "Server-side JSON.parse for trusted strings" },
  { api: "global.JSON.stringify()", desc: "Serialize a value to JSON in global scope" },
  { api: "GlideRecord.setReplyTo()", desc: "Set Reply-To when sending notifications from GR" },
  { api: "NotifyNow.sendNotification()", desc: "Trigger a Notify Now SMS or voice message" },
  { api: "SNC.IPAddressV4.isInRange()", desc: "Check whether an IPv4 falls inside a CIDR" },
  { api: "GlideRecord.setMultiNodeStrategy()", desc: "Hint multi-node parallelism for big queries" },
  { api: "GlideStorageService.write()", desc: "Stream bytes into an attachment-style store" },
  { api: "GlideStorageService.read()", desc: "Stream bytes out of an attachment-style store" },
  { api: "GlideSysAttachment.write()", desc: "Attach a file to a record from script" },
  { api: "GlideSysAttachment.copy()", desc: "Copy attachments between two records" },
  { api: "GlideSysAttachment.deleteAttachment()", desc: "Delete an attachment by sys_id" },
  { api: "GlideSysAttachment.getContent()", desc: "Return attachment bytes as a string" },
  { api: "GlideRecord.setLocation()", desc: "Force a query to a specific data center node" },
  { api: "GlideRecord.setHavingClause()", desc: "Apply a HAVING clause to a grouped query" },
  { api: "GlideMetric", desc: "Server-side counter/timer for performance dashboards" },
  { api: "GlideTextSearch", desc: "Wrapper around Zing full-text search" },
  { api: "GlideTextSearch.search()", desc: "Execute a global text search returning matches" },
  { api: "GlideExportSet.export()", desc: "Programmatically export records to a file format" },
  { api: "GlideScriptedProcessor", desc: "Custom processor invoked by a URL path" },
  { api: "GlideController.getAttribute()", desc: "Read a UI controller attribute from script" },
  { api: "GlideUITransaction.getURI()", desc: "URI of the currently-rendered UI transaction" },
  { api: "GlideDialogWindow", desc: "Open a modal dialog from a UI macro" },
  { api: "GlideListV3", desc: "Programmatic handle on a list/list view" },
  { api: "GlideRecord.setForceWorkflow()", desc: "Force workflow evaluation even when disabled" },
  { api: "GlideRecord.getValueByDotwalk()", desc: "Read a dot-walked reference field value" },
  { api: "GlideAggregate.queryNoDomain()", desc: "Run the aggregate ignoring domain separation" },
  { api: "GlideDigest.getMD5Base64()", desc: "MD5 hash of a string, base64-encoded" },
  { api: "GlideUser.getDomainID()", desc: "Domain sys_id the GlideUser belongs to" },
  { api: "GlideDateTime.toString()", desc: "Internal UTC string in yyyy-MM-dd HH:mm:ss" },
  { api: "GlideDateTime.fromUserDateTime()", desc: "Build a GDT from a user-formatted string" },
  { api: "GlideDateUtil.getQuartersBetween()", desc: "Count of fiscal quarters spanning two dates" },
  { api: "GlideTime.getByFormat()", desc: "Format a GlideTime using a custom pattern" },
  { api: "GlideDate.getByFormat()", desc: "Format a GlideDate using a custom pattern" },
  { api: "GlideDateTime.getWeekOfYearLocalTime()", desc: "Week-of-year index in the user's time zone" },
  { api: "GlideRecord.setExcludeDomainSeparator()", desc: "Bypass domain separator on this query" },
];

// ---------- BONUS (mixed difficulty fillers to push pool past 300) ----------
export const BONUS: Pair[] = [
  { api: "g_form.addOption()", desc: "Add a choice to a choice-list field on the form" },
  { api: "g_form.removeOption()", desc: "Remove a choice from a choice-list field" },
  { api: "g_form.clearOptions()", desc: "Empty all options from a choice-list field" },
  { api: "g_form.flash()", desc: "Briefly highlight a field with a color flash" },
  { api: "g_form.getSectionNames()", desc: "Array of section names currently on the form" },
  { api: "g_form.setSectionDisplay()", desc: "Show or hide a whole form section" },
  { api: "g_form.getTableName()", desc: "Name of the table the current form belongs to" },
  { api: "g_form.getUniqueValue()", desc: "Client-side sys_id of the record being edited" },
  { api: "g_form.disableAttachments()", desc: "Hide the attachment paperclip on the form" },
  { api: "g_form.enableAttachments()", desc: "Re-enable attachments on the form" },
  { api: "g_list.refresh()", desc: "Force a related list to reload its data" },
  { api: "g_list.getQuery()", desc: "Encoded query currently filtering the list" },
  { api: "g_list.setOrderBy()", desc: "Change the sort order of a related list" },
  { api: "g_menu.addAction()", desc: "Add a custom action to a context menu" },
  { api: "g_modal.showFrame()", desc: "Open a modal that hosts an iframe URL" },
  { api: "g_modal.confirm()", desc: "Show a confirm dialog returning a promise" },
  { api: "g_modal.alert()", desc: "Show a single-button alert dialog" },
  { api: "spUtil.get()", desc: "Service Portal helper to fetch widget data" },
  { api: "spUtil.update()", desc: "Re-run a widget's server script and re-render" },
  { api: "spUtil.addInfoMessage()", desc: "Portal-aware info banner via spUtil" },
  { api: "spUtil.addErrorMessage()", desc: "Portal-aware error banner via spUtil" },
  { api: "spUtil.recordWatch()", desc: "Live-update a widget when a record changes" },
  { api: "$sp.getRecord()", desc: "Server-side portal helper for the current record" },
  { api: "$sp.getValue()", desc: "Read a field from the portal's current record" },
  { api: "$sp.getCatalogItem()", desc: "Load a catalog item definition in a portal widget" },
  { api: "gs.urlEncode()", desc: "URL-encode a string for safe query params" },
  { api: "gs.base64Encode()", desc: "Base64-encode a string (global wrapper)" },
  { api: "gs.base64Decode()", desc: "Base64-decode a string (global wrapper)" },
  { api: "gs.xmlToJSON()", desc: "Convert an XML string to a JSON object" },
  { api: "gs.jsonToXML()", desc: "Convert a JSON object to an XML string" },
  { api: "gs.print()", desc: "Print to the Background Scripts output panel" },
  { api: "gs.flushMessages()", desc: "Discard queued info/error messages" },
  { api: "gs.getMessages()", desc: "Look up multiple translated messages at once" },
  { api: "gs.dateDiff()", desc: "Difference between two date strings as a duration" },
  { api: "gs.calDateDiff()", desc: "Calendar day count between two date strings" },
  { api: "GlideRecord.setBatchUpdateMode()", desc: "Buffer updates and flush in one DB round-trip" },
  { api: "GlideRecord.disableNotification()", desc: "Skip notification engine for the next save" },
  { api: "GlideRecord.enableNotification()", desc: "Re-enable notifications after disabling them" },
  { api: "GlideRecord.getRefRecord()", desc: "Fetch the referenced record for a reference field" },
  { api: "GlideRecord.getElements()", desc: "Array of GlideElement objects on this row" },
  { api: "GlideElement.getName()", desc: "Internal column name of the GlideElement" },
  { api: "GlideElement.getTableName()", desc: "Table this field belongs to" },
  { api: "GlideElement.setJournalEntry()", desc: "Append text into a journal-type field" },
  { api: "GlideElement.setDateNumericValue()", desc: "Set a date field from epoch milliseconds" },
  { api: "GlideElement.dateNumericValue()", desc: "Epoch ms of the underlying date field" },
  { api: "sn_notification.Messaging.send()", desc: "Send a Notify message via a configured provider" },
  { api: "sn_auth.GlideOAuthClient.requestToken()", desc: "Request an OAuth access token from the provider" },
  { api: "sn_auth.GlideOAuthClient.refreshToken()", desc: "Refresh an OAuth token using its refresh token" },
  { api: "sn_cc.ConnectionInfoProvider", desc: "Resolve a Connection & Credential alias to creds" },
  { api: "sn_cc.StandardCredentialsProvider", desc: "Provider that yields credentials by alias name" },
  { api: "GlideRecord.setSysFieldsOnInsert()", desc: "Control which sys_* fields populate on insert" },
  { api: "GlideRecord.getDisplayName()", desc: "Display field value of the record (e.g. number)" },
  { api: "GlideAggregate.setGroup()", desc: "Toggle grouping on or off without removing it" },
  { api: "GlideAggregate.orderByAggregate()", desc: "Sort results by an aggregate value" },
  { api: "GlideRecord.serialize()", desc: "Serialize the current row to JSON" },
];

export const POOL: Pair[] = [...EASY, ...MEDIUM, ...HARD, ...EXPERT, ...BONUS];

// Total pair count is enforced by a unit-test friendly assertion the dev
// can sanity-check: POOL.length >= 300.
